name: Django CI

on:
  push:
    branches: [ "Refactoring" ]
  pull_request:
    branches: [ "Refactoring" ]

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./CargoHub

  # Test Job
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./CargoHub
      - name: Test with pytest
        run: |
          pytest
        working-directory: ./CargoHub

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 145.24.223.64
          username: ubuntu-1021342
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBcSP4Dx1F9LAMRqqXUviZKASf8UARuoF1tGZWiSFdvFNdRO0afFCvZ0Uuz2yqp4bM35RJEHgiSl/SaaarxbpVv+SLYYQvVCXr/P1TPlUZxdLyM1hQBbeGAHoJsKcaGlobQw1RD56DfBc03SwSydAGGWzDGWWyQxaMVewP6LSCY3R2rMt51Sboaw+NfAboJv+RHRrkZYMswx1Vh87oyg5+jCBQpUoVzgs1yd474cHCLB14jqevBlH92s2SSPZYDcGuUu+LSzbeV+lGU07Hnt7IklSY2oZYaYIuGAj1IhIdFi5W1IgWo7KY3sBTnqH7VlyZkijH4JHvZH+AvkiXefNhuzPFumtRmPR+z3D4NOOIN010u/1tiFG/J0eGXizr2qu1685DN3jBKCKw3uCvmMM58ZnkzwKa+0StpTyn8U1upNzR5t/8O13FZf5T20snQo7DHz00fpU326i4cXIgEJuSKmHqx5T45tmf2actvRIv3qbgXEKvriL/97tEVDGQRtgf8BmLMugZUDwz4536Lcd8y5eSVOkfknKqysrChYeVZfR8jpC32tf+rUqBWnHlz9r952/HOoJ22ftzpUSgzMn8LPN7vgJFCJaN7Xhx8I+3l8NPLJRqZ664zjgAdJVFJX0jKFHXAuO6qs2fHpHJywlwhCwKzkN2M8pnAauwZc/wKw== 1021342@hr.nl
          port: 22
          script: |
            cd /home/ubuntu-1021342/Repo/Process-and-Tools/CargoHub
            git pull origin Refactoring
            source /home/ubuntu-1021342/Repo/Process-and-Tools/CargoHub/venv/bin
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart django
          timeout: 300s  # Timeout in seconds (5 minutes)
